export enum Symbol {
    Cross = "cross",
    Circle = "circle",
    Square = "square",
    Triangle = "triangle",
    Losange = "losange",
    Pentagon = "pentagon",
    Star = "star",
    Heart = "heart",
    Emoji = "emoji",
    Tennis = "tennis_ball",
    Web = "web",
    Asterisk = "asterisk",
    Bot = "bot",
    Percent = "percent",
    Compass = "compass",
    Moon = "moon",
}